// This file is autogenerated by Simplicity Configuration Tools.
// The contents of this file will be replaced in their entirety upon regeneration.
// 
// Source template file: sl_wisun_keychain_builtin.c.jinja


#include <stdint.h>
#include <stdlib.h>
#include "sl_wisun_keychain.h"

const uint32_t sl_wisun_keychain_builtin_trustedca_count = 0;
const sl_wisun_keychain_entry_t sl_wisun_keychain_builtin_trustedca[] = {
  { NULL, 0, SL_WISUN_KEYCHAIN_BUILTIN }
};

const uint32_t sl_wisun_keychain_builtin_devicecert_count = 0;
const sl_wisun_keychain_entry_t sl_wisun_keychain_builtin_devicecert[] = {
  { NULL, 0, SL_WISUN_KEYCHAIN_BUILTIN }
};

const uint32_t sl_wisun_keychain_builtin_devicekey_count = 0;
const sl_wisun_keychain_entry_t sl_wisun_keychain_builtin_devicekey[] = {
  { NULL, 0, SL_WISUN_KEYCHAIN_BUILTIN }
};
